### ISSUE TITLE
Error al instalar en debian

### ISSUE THREAD

**Issue by Jubamo** [luarvique/ppa#1]
Hola, 
he probado a instalarlo en un contenedor de debian y da error al instalar, el paquete esta comprimido con zst y el dpkg de debian no lo soporta. La version debian de JaKob si que la instala bien.
Por otro lado en un contenedor con ubuntu si lo instala correctamente y funciona con rtl-sdr.

Un saludo,
Juan.
![2022-12-28 at 07 06 12](https://user-images.githubusercontent.com/106386775/209807509-c9b985d4-788f-4109-aef2-ca7af0745f0c.jpeg)

**Comment by luarvique** [comment]
I think your system might be missing something, since "unknown compression" is not the only error there. What is your OS an architecture?

**Comment by Jubamo** [comment]
Linux IdeaPad-5 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

No lo he probado con debian nativo, solo con la imagen docker "docker.io/library/debian    bullseye-slim" 

![error](https://user-images.githubusercontent.com/106386775/209854396-3b3b6d64-c3ed-47bb-adf3-ab64df932f87.jpeg)

**Comment by luarvique** [comment]
Well, I cannot help you with Docker, sorry. Try using real operating system instead.

**Comment by Jubamo** [comment]
Ya lo puedo instalar,
Todas las pruebas las hago con docker y observo lo siguiente:
 
debian bookworm -> se instala correctamente su version, en cambio para la oficial no se cumplen las dependencias.

debian bullseye ->  se instala correctamente la oficial  y su version no cumle las dependencias.

Ps.- Creo que su paquete esta creado para la version debian bookworm (unstable) y el oficial para debian bullseye (stable).

**Comment by Jubamo** [comment]
Con los cambios de hoy, ya se instala i funciona en debian bullseye.
