### ISSUE TITLE
sdrplay设备在dokcer下没有瀑布和声音

### ISSUE THREAD

**Issue by 413137366** [luarvique/ppa#10]
经过查看日志后来发现https://github.com/luarvique/owrx_connector中的组件缺少
(optional) If you want to work with devices supported by SoapySDR, you will need to install the corresponding header files (on Debian: apt-get install libsoapysdr-dev)

安装后libsoapysdr-dev后正常，希望可以帮到其他人。

**Comment by luarvique** [comment]
Sorry, but what exactly do you mean? Why do you need header files?

**Comment by 413137366** [comment]
我使用的是设备是rsp1+armbian，安装docker版openwebrxplus（slechev/openwebrxplus）后发现没有声音，安装libsoapysdr-dev后正常，希望可以将此软件集成到docker镜像中。

**Comment by 0xAF** [comment]
> 我使用的是设备是rsp1+armbian，安装docker版openwebrxplus（slechev/openwebrxplus）后发现没有声音，安装libsoapysdr-dev后正常，希望可以将此软件集成到docker镜像中。

Can you please try with the latest image and report?
It has the same tags, so force pull from docker hub.

**Comment by 413137366** [comment]
重新下载了最新的docker版openwebrxplus镜像，rsp1设备工作正常，感谢付出。
