### ISSUE TITLE
DMR decoder not enabled ? installed ? 

### ISSUE THREAD

**Issue by LeFEAR** [luarvique/ppa#11]
Dear Sir , 

I would like to know if I am doing something wrong , I want to also have DMR decoder on my OW+ 
Because I am using an ubuntu VM and I can't use docker or RPI ( due to material shortage ) 
I would like to know what I need to do to able DMR decoding function on my OWRX+ server. 

Thank you in advance

**Comment by luarvique** [comment]
See here for instructions

https://github.com/jketterl/openwebrx/wiki/AMBE-vocoder-device-notes

**Comment by Klammraute** [comment]
whats with mbelib?

**Comment by luarvique** [comment]
https://fms.komkon.org/OWRX/#FAQ3

**Comment by Klammraute** [comment]
I done that but it dont shows up

**Comment by luarvique** [comment]
https://fms.komkon.org/OWRX/#FAQ3

**Comment by Klammraute** [comment]
i did that, but it doesent work, even when i reboot

**Comment by luarvique** [comment]
https://fms.komkon.org/OWRX/#FAQ3
