### ISSUE TITLE
Error when i try to install

### ISSUE THREAD

**Issue by IZ0FIU** [luarvique/ppa#12]
seguenti pacchetti hanno dipendenze non soddisfatte:
 python3-csdr : Dipende: python3 (< 3.11) ma la versione 3.11.2-1 sta per essere installata
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

ppa is ok. How can i resolve?

**Comment by luarvique** [comment]
You are trying to install it on a wrong operating system.
