### ISSUE TITLE
Feature request: "Shown center frequency" for users with upconverters

### ISSUE THREAD

**Issue by JJi-588** [luarvique/ppa#14]
Hello!
Back in the early days, OpenWebRX had a configuration option for users with upconverters.
It was located in config_webrx.py file as "shown_center_frequency=" and setting this value to the desired value caused the UI to show the set value instead of upconverter frequency + desired frequency.

In my case, the upconverter is the Spyverter with 120MHz upconversion, so if I want to tune to 4.625MHz to hear the good old russian buzzer UVB76, I need to use a frequency of 124.625MHz instead. As the frequency is different, the bookmarks set for lower frequencies don't show.

This option is shown in the old configuration file behind this link:
https://github.com/ha7ilm/openwebrx/blob/76350936794dc21da313b842b95fab17eda5372f/config_webrx.py#L111

If this is not already implemented, I would love to see this as an option for profiles.
If this probability already exists, can you point me to the right direction?

**Comment by luarvique** [comment]
This should not be a function of OWRX. Has to be resolved in the driver, such as Soapy.
