### ISSUE TITLE
SAM missing after upgrade to OpenWebRX+ 1.2.30

### ISSUE THREAD

**Issue by JJi-588** [luarvique/ppa#15]
Hi!
After upgrading OpenWebRX+ to the latest version (1.2.30), SAM has disappeared from the list. SAM was available in a previous version (1.2.29). Is this expected behavior? 

I'm running OpenWebRX+ in Ubuntu 22.04 (Jammy Jellyfish), amd64, minimized setup.

**Comment by luarvique** [comment]
This will be fixed in the next release.
