### ISSUE TITLE
Installation on Debian 12

### ISSUE THREAD

**Issue by Jelmate** [luarvique/ppa#16]
I try to follow your description of installing Openwebrx+ on my Debian 12 server but after running the apt install openwebrx command I get the error:

The following packages have unmet dependencies:
 python3-csdr : Depends: python3 (< 3.10) but 3.11.2-1+b1 is to be installed
 soapy-connector : Depends: libsoapysdr0.7 (>= 0.7.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

Is it possible to recompile your version of openwebrx+ so it can also run on the latest version of Debian?

**Comment by luarvique** [comment]
It is possible, but you will have to do it yourself. All the source code is on GitHub.
