### ISSUE TITLE
Feature request: "Possibility to block users by IP/ end current connected sessions"

### ISSUE THREAD

**Issue by toiosoiovoio** [luarvique/ppa#19]
Hi,

Its a two in one feature request. The possibility to block a given IP adddress from connecting to OWRX+ and the possibility to end current connected sessions on OWRX+, not all at once but specific ones, in the settings page.

Even if not possible I take to opportunity say thank you for all the effort you guys put into OWRX.

Rui Delgado

**Comment by luarvique** [comment]
This is now implemented, starting with OWRX+ 1.2.39.
