### ISSUE TITLE
Activate SSB AGC profile slowly

### ISSUE THREAD

**Issue by dh9yap** [luarvique/ppa#21]
Hello
I want to slowly activate the AGC profile for SSB. In which file do I have to change this? Perhaps this can still be implemented in the receiver menu?

**Comment by luarvique** [comment]
You have to change this:

https://github.com/luarvique/openwebrx/blob/d099dd92d3841973f61f1a3df41ca8e7314d2faf/csdr/chain/analog.py#L70
