### ISSUE TITLE
multimon-ng charset parameter

### ISSUE THREAD

**Issue by stylesuxx** [luarvique/ppa#25]
`multimon-ng` supports a charset parameter (which can be one of the following options: US,FR,DE,SE,SI)
Would be cool if this could be a dropdown in the "Misc" section where the other pager related setting is.

I am aware that this is rather a feature request for https://github.com/luarvique/openwebrx - but since the issues there are not enabled I thought I'd give it a shot over here.

**Comment by luarvique** [comment]
This has been implemented and will be out with the next release,
