### ISSUE TITLE
I had to reinstall Openwebrx+ now ISM stopped decoding.

### ISSUE THREAD

**Issue by Nhscan** [luarvique/ppa#27]
I had to reinstall Openwebrx+ now ISM stopped decoding. I did a full uninstall reinstall of openwebRX pluss. Now it will not decode ISM. Why I had to reinstall was after upgrading and updating the system OS openwebrx stopped working So i removed and reinstalled I really hat to have to redo the whole system. Any tips on getting this working without? all dependencies are installed I don;t get it.

**Comment by luarvique** [comment]
Sorry, but I do not know what is wrong. ISM works here:
![image](https://github.com/luarvique/ppa/assets/3293202/b10408f6-ab49-4350-b79a-6bc4f80fd06b)

**Comment by Nhscan** [comment]
Thanks for getting right back to be. Yeah mine was working fine as well not sure what is going on other Decoders working fine just seems to be ISM not sure what it is as well. I have 3 very common weather stations that I recive with rtl-433 just fine on windows I even reinstalled just rtl-433 on this box and still not go.

![11](https://github.com/luarvique/ppa/assets/135085856/40bdfbd3-22cd-4174-8f0b-d9f32f39d2d7)
