### ISSUE TITLE
soapysdr-module-sdrplay3 requires SDRplay API 3.14, I want to stay with 3.12

### ISSUE THREAD

**Issue by timo12357** [luarvique/ppa#28]
Hi, 
after upgrade soapysdr-module-sdrplay3 started requirin SDRplay API 3.14. I do not want to upgrade the API to 3.14. 
Please advice how to regress back to a version of soapysdr-module-sdrplay3 that is happy with SDRPlay API 3.12.

**Comment by luarvique** [comment]
Use soapysdr-module-sdrplay3 0.8.7, still available from the repo.
