### ISSUE TITLE
LOCK Channel (When logged in as Admin)

### ISSUE THREAD

**Issue by troyBORG** [luarvique/ppa#31]
There are times when at work during some kinda Tornado Warning, and I want to listen to the local 2m band for reports while stuck in our work Storm Shelter.

Well there are times when I'm doing that, someone will also login to my SDR, and will change it from the 2m band to the Police/Fire/EMS channel to listen to that, tearing me away from hearing important info.  

I know i can login and use this "Magic key" thing (Which I have never been able to figure out how the hell that works).
But that will stop people from changing the channels on me.

But I would like to have just a button on the Receiver, that when I'm logged in, I can click and lock it down from being changed on the tuner that I'm using.

**Comment by luarvique** [comment]
Sorry, but you will have to use the "Magic key" thing. Or limit the number of users to 1.

**Comment by troyBORG** [comment]
Yeah but that means I have to switch it to the channel I want, login go turn on and save it with it turned on, and hope the person also listening doesn't try to change it off the channel i want before I can click save it time.

You never explained how this Magic Key thing works.  I tried and even with the phrase I set, it still doesn't let me change channels.

Also what if someone is already on the SDR.   

I just want it, that if the ADMIN of the SDR is on, and I change the channel.   That until I leave, it will stay on that channel.     
But if other then join they can change channels, untill I log in, and then change it to what I wanna listen to, as its my SDR.

**Comment by troyBORG** [comment]
Like mostly when I'm logged in, it would be as though the "Require magic key to switch profiles on this device" bool with be checked.
Then when I'm no longer connected, for so long then turn the "Require magic key" back off again so people can use it like normal.

**Comment by luarvique** [comment]
Well, it is in the FAQ section of the documentation, available by oressing the question mark icon:

https://fms.komkon.org/OWRX/#FAQ-PROFILES
