### ISSUE TITLE
deb-src url

### ISSUE THREAD

**Issue by arekm** [luarvique/ppa#32]
What is apt "deb-src" url for this ppa?

I'm trying to run it on debian trixie (it's debian testing branch; future stable). I do that because trixie contains much newer sdr related libraries like librtl 2.0.2 and not 0.6 etc.

Unfortunately some binaries require rebuilding and for that source files would be handy to get for example 'apt-get source python3-csdr' working.

Tried
deb-src [signed-by=/etc/apt/trusted.gpg.d/openwebrx-plus.gpg] https://luarvique.github.io/ppa/bookworm ./
but such repo is not available.

If src repo is not published then please consider adding it to ppa.

**Comment by arekm** [comment]
buildall.sh worked nicely on trixie (only one fix was needed (sed -i -e 's#build/redsea#src/redsea#g' debian/install)

Thanks.

**Comment by luarvique** [comment]
Wonderful!
