### ISSUE TITLE
Nginx reverse-proxy - log 404 error

### ISSUE THREAD

**Issue by sq4bja** [luarvique/ppa#4]
Hi,
I`m using Nginx as Reverse proxy to Openwebrx+.
I found some errors in nginx logs (404 - file not found):
```
GET /settings/static/gfx/svg-defs.svg HTTP/1.1" 404
GET /settings/sdr/rtl_sdr_h/profile/static/gfx/svg-defs.svg HTTP/1.1" 404
GET /favicon.ico HTTP/1.1" 404

```
What is wrong?

**Comment by luarvique** [comment]
No idea, but it probably means you should not be using Nginx as reverse
proxy. Because it appears to be sticking "static/gfx/svg-defs.svg" all over
the place, just not where this file really is.

Best regards,
  Marat Fayzullin

**Comment by luarvique** [comment]
Which page of the configuration? Also, OWRX+ now offers built-in HTTPS
support, so you do not need to use Nginx for that.

**Comment by luarvique** [comment]
Sorry, but I am not seeing this error. Thus, it must be specific to your
networking setup.

Best regards,
  Marat Fayzullin
