### ISSUE TITLE
Feature Request : Add AIS report to https://www.vesselfinder.com

### ISSUE THREAD

**Issue by fouine95** [luarvique/ppa#5]
Feature description:
Add options to allow to report AIS (APRS like) to https://www.vesselfinder.com/ API (udp / @ip / port)

Target audience
Everyone using openwebrx to listen AIS traffic and want to share with vesselfinder

thank you :)

**Comment by luarvique** [comment]
AIS in OWRX+ is processed and reported by Direwolf. If Direwolf cannot report to wherever you want, neither can OWRX+.

**Comment by fouine95** [comment]
i think APRS is reported by Direwolf too, and report feature to APRS-IS server/network is enable in OWRX

**Comment by luarvique** [comment]
I have checked and it does not appear like Direwolf can report stuff to vesselfinder.com. Sorry.
