### ISSUE TITLE
Feature Request: auto switch to incoming signal

### ISSUE THREAD

**Issue by fouine95** [luarvique/ppa#6]
Use case:

i'am listening a bandwith from 155Mhz to 157Mhz.

I have already ploted some bookmarks on this bandwith.

i would like a feature that auto jump/switch from a bookmark to another (in the same profil) after a silence (based on autoSquelch setting), at signal incoming.

ex : i am listening to Bookmark1 (155,450Mhz). After 20sec of silence, auto switch is actived. When a signal incoming to Bookmark5 (156,500Mhz), tuner auto jump to this channel for listening. After another 20sec of silence, auto switch is actived again.

**Comment by atlex** [comment]
Nice feature. Looks like a scanner :)

**Comment by luarvique** [comment]
This feature has been discussed previously. Right now, I do not have time to implement it, but you can try. Let me know what comes out of this. Here is the OWRX+ source code: https://github.com/luarvique/openwebrx/tree/master

**Comment by luarvique** [comment]
The scanner has been implemented now.

**Comment by fouine95** [comment]
> The scanner has been implemented now.

Woooo! Excelent :) Thank you very MUCH
