### ISSUE TITLE
How to update SoapySDR on remote site?

### ISSUE THREAD

**Issue by timo12357** [luarvique/ppa#7]
I just updated the Soapy SDR module with

`apt install soapysdr-module-sdrplay3`

on my remote RSPdx on Raspberry PI4. Seems like this update should be done with the RSP disconnected from the Raspberry, as now my RSP did not start up. Even after three reboots the RSP did unfortunately not start. Is there a way to get it up without having to actually physically disconnect the RSP from the Raspi? As the RX is in a remote location I would rather not have to make the trip there.

**Comment by timo12357** [comment]
Found some errors in the log, seems the SoapySDR library can not be found:
`● openwebrx.service - OpenWebRX WebSDR receiver
     Loaded: loaded (/etc/systemd/system/openwebrx.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-04-22 16:01:55 EEST; 4s ago
   Main PID: 1795 (openwebrx)
      Tasks: 1 (limit: 3720)
        CPU: 660ms
     CGroup: /system.slice/openwebrx.service
             └─1795 /usr/bin/python3 /usr/bin/openwebrx

Apr 22 16:01:55 openwebrx systemd[1]: Started OpenWebRX WebSDR receiver.
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,894 - owrx.__main__ - INFO - OpenWebRX+ version v1.2.11 starting up...
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,898 - owrx.config.migration - DEBUG - migrating config from version 1
Apr 22 16:01:55 openwebrx openwebrx[1796]: soapy_connector: error while loading shared libraries: libSoapySDR.so.0.8-2: cannot open shared object file: No such file or directory
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,912 - owrx.sdr - ERROR - The SDR source type "sdrplay" is not available. please check the feature report for details.
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,920 - owrx.__main__ - INFO - No SSL certificate, using http:// protocol.
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,920 - owrx.__main__ - INFO - To enable https://, supply SSL certificate:
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,920 - owrx.__main__ - INFO -     /etc/openwebrx/cert.pem
Apr 22 16:01:55 openwebrx openwebrx[1795]: 2023-04-22 16:01:55,920 - owrx.__main__ - INFO -     /etc/openwebrx/key.pem
`

**Comment by luarvique** [comment]
No, you do no need to physically disconnect the RSP when installing this package. As to the missing library message, it is unusual, but should be fixable by installing that library package.

**Comment by timo12357** [comment]
What library should be installed and how? There seems to be no way to install the soapy-connector that owrx would recognize.
![image](https://user-images.githubusercontent.com/11517762/233818560-9d71bc1e-cf41-4b04-896c-d6a5ebe1cf9a.png)

**Comment by luarvique** [comment]
> What library should be installed and how? There seems to be no way to install the soapy-connector that owrx would recognize. 

libsoapysdr0.8

**Comment by timo12357** [comment]
There is no such package in the repo. How to install?

Is this correct:
`sudo apt purge soapysdr0.7-module-sdrplay3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  soapysdr-module-sdrplay3* soapysdr0.7-module-sdrplay3*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 146 kB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
`
soapysd-module-sdrplay3 has a dependency to soapysdr0.7-module-sdrplay3. Is this a conflct?

**Comment by luarvique** [comment]
Sorry, but at this point I have no idea what you are doing. For what it is worth, soapy_connector asked for libSoapySDR 0.8, not 0.7. You must be doing something very wrong.

**Comment by timo12357** [comment]
I am on RaspberryPi  4, I removed the old install with 
`sudo apt purge openwebrx
sudo apt purge soapysdr-module-sdrplay3`

Rebooted and then
`sudo apt install openwebrx
sudo apt install soapysdr-module-sdrplay3`

Digging into this a bit: 
`$ sudo apt info libsoapysdr0.7
Package: libsoapysdr0.7
Version: 0.7.2-2
Priority: optional
Section: libs
Source: soapysdr
Maintainer: Debian Hamradio Maintainers <debian-hams@lists.debian.org>
Installed-Size: 319 kB
Depends: libc6 (>= 2.27), libgcc-s1 (>= 3.5), libstdc++6 (>= 7)
Recommends: soapysdr0.7-module-all | soapysdr0.7-module
Homepage: https://github.com/pothosware/SoapySDR/wiki
Download-Size: 88.1 kB
APT-Manual-Installed: no
APT-Sources: http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
Description: software defined radio interface library
 SoapySDR is a library providing a common interface to SDR (software
 defined radio) hardware. Support for different hardware is added through
 external modules.
 .
 This package contains the shared library.
`
And:
`$ sudo apt info libsoapysdr0.8
N: Unable to locate package libsoapysdr0.8
N: Couldn't find any package by glob 'libsoapysdr0.8'
N: Unable to locate package libsoapysdr0.8
N: Couldn't find any package by glob 'libsoapysdr0.8'
E: No packages found
`
There is no libsoapysdr0.8 in the Raspbian repo.

**Comment by luarvique** [comment]
You might be installing from Ubuntu repo rather than Debian. Please, read instructions carefully.
