### ISSUE TITLE
Feature Request: Offline Map

### ISSUE THREAD

**Issue by chjohn22** [luarvique/ppa#8]
Would be cool to have an offline map to use the Raspberry in the mountains without internet.
We could have a live AIS and APRS overview map. By providing a map tile server endpoint in the settings, for example in the XYZ format, hosted with https://github.com/maptiler/tileserver-gl.

**Comment by luarvique** [comment]
The current map is implemented using Google Maps service. If you would like to implement a different version of the map, feel free to go ahead with your project and let me know what comes out of it.
